# Generated by Django 5.1.3 on 2025-06-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subschool',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.subschool'),
        ),
    ]
