# Generated by Django 5.1.3 on 2025-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_course_subschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='subschool',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
