# Generated by Django 5.1.3 on 2025-08-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_student_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('schedule', 'course')},
        ),
    ]
